version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: spring-app
    restart: always
    depends_on:
      - cache
    env_file:
      - DockerEnv.env
    ports:
      - "9001:8080"
    networks:
      - durimong-network

  cache:
    image: redis:latest
    container_name: redis-container
    restart: always
    env_file:
      - DockerEnv.env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - durimong-network


volumes:
  redis_data:
 
networks:
  durimong-network:
