spring:
  application:
    name: durymong
  web:
    resources:
      add-mappings: false
  profiles:
    group:
      local: local-db, dev-port, common
      dev: dev-db, dev-port, common
      prod: prod-db, prod-port, common
    active: dev

---
# 로컬용 DB
spring:
  config:
    activate:
      on-profile: local-db
  datasource:
    url: ${LOCAL_DATASOURCE_URL}
    username: ${LOCAL_DATASOURCE_USERNAME}
    password: ${LOCAL_DATASOURCE_PASSWORD}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
  data:
    redis:
      host: localhost
      port: 6379

---
# 개발용 DB
spring:
  config:
    activate:
      on-profile: dev-db
  datasource:
    url: ${DEV_DATASOURCE_URL}
    username: ${DEV_DATASOURCE_USERNAME}
    password: ${DEV_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
        highlight_sql: true
  data:
    redis:
      host: localhost
      port: 6379


---
# 배포용 DB
spring:
  config:
    activate:
      on-profile: prod-db
  datasource:
    url: ${PROD_DATASOURCE_URL}
    username: ${PROD_DATASOURCE_USERNAME}
    password: ${PROD_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379

---
# 개발용 포트
spring:
  config:
    activate:
      on-profile: dev-port
server:
  port: 9001
---
# 배포용 포트
spring:
  config:
    activate:
      on-profile: prod-port
server:
  port: 9002
---
# 공통
spring:
  config:
    activate:
      on-profile: common
  docker:
        compose:
          enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: idwjddus1112@gmail.com
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000
  openai:
    api:
      url: https://api.openai.com/v1/chat/completions
      key: ${OPENAI_API_KEY}

jwt:
  secret: ${JWT_SECRET}
  accessTokenExpiration: 3600000
  refreshTokenExpiration: 604800000